<?php
/**
 *
 * @package   User
 * @filename  UserRepository.php
 * @author    renyineng <renyineng@kmf.com>
 * @license   http://www.kmf.com/ kmf license
 * @datetime  17/2/20 上午10:36
 */
namespace App\Repositories;

use App\Models\todayHeadline;

class TodayHeadlineRepository extends BaseRepository
{
    protected $model;
    public function __construct(todayHeadline $model)
    {
        $this->model = $model;
    }

    public function getInfoById($id){
        $ret = [];
        if(is_numeric($id) && $id>0){
            $ret = $this->model->where('id',$id)->get();
        }
        return $ret;
    }


    public function add($data){
        if(empty($data)){
            return false;
        }
        $arrInsert = array(
            "star_id" => $data['star_id'],
            "star_name" => $data['star_name'],
            "title" => isset($data['title'])?$data['title']:'',
            "left_pic_urls" => isset($data['left_pic_urls'])?$data['left_pic_urls']:'',
            "nike_name" => isset($data['nike_name'])?$data['nike_name']:'',
            "publish_date" => isset($data['publish_date'])?$data['publish_date']:'',
            "video_flag" => isset($data['video_flag'])?$data['video_flag']:2,
        );
        $ret = $this->model->create($arrInsert);
        return $ret;
    }

    public function getDataList($where, $column = ['*'], $group = '', $sort = [], $page = 1, $limit = 10, $with = '', $whereIn = [])
    {
        return parent::getDataList($where, $column, $group, $sort, $page, $limit, $with, $whereIn); // TODO: Change the autogenerated stub
    }


}